
a = 10
b = 20
c = a + b
print(c)

try:
    print(10)
except Exception:
    print('An exception occurred')
